### ISSUE TITLE
Is Jenkspy available for Python 3?

### ISSUE THREAD

**Issue by Irene-GM** [mthh/jenkspy#1]
Hi,

I would like to know whether there is a version of `jenkspy` for Python 3 and, if so, how can I install it from pip/conda? When I use the commands suggested in the documentation, it tries to downgrade my Python 3 to 2, and I would prefer just to stick to Python 3.

Thanks for the effort!
Irene

**Comment by mthh** [comment]
Sure! You can install it for python3 by doing :
```
pip3 install jenkspy
```
There is wheels provided for windows users (for python version 2.7, 3.4, 3.5 and 3.6, both 32 and 64 bits).

If you are using anaconda for python 3 (I just tested it on a fresh anaconda installation) you can install it by doing : 
```
conda install -c conda-forge jenkspy 
```
(in my case I used the conda binary located in `~/anaconda3/bin/`)

If it doesn't solve your issue, don't hesitate to provide more informations about your environment (which OS, which python version, etc.) and the error you are encountering.

**Comment by Irene-GM** [comment]
Yes! It worked perfectly!  I forgot to mention that I was in Windows, so I went to the conda environment containing this `pip.exe` (for Python 3.4) and used the command you suggested. Thanks!

**Comment by mthh** [comment]
Glad it helped!
