### ISSUE TITLE
KeyError: 20

### ISSUE THREAD

**Issue by iptriant** [mthh/jenkspy#18]
Hi everyone. I am trying to get the natural breaks of a geodataframe column. Even though the data type is float64, I am getting a KeyError: 20. Does anyone know what might be wrong ? Thanks in  advance  

![error](https://user-images.githubusercontent.com/51904766/132656441-f450a5a9-74ba-4c21-8d10-c30aca42d0df.PNG)

**Comment by mthh** [comment]
`jenkspy.jenks_breaks` does not natively support `pandas.Series`.
You should transform your values into a numpy array first, using the `to_numpy` method (with something like `buurten_perfomance['A_obstacle'].to_numpy()`).

Hope this helps. Don't hesitate to tell if you still have a problem.

**Comment by iptriant** [comment]
Dear @mthh. Firstly, thanks a lot for the reply. I tremendously appreciate it. Your solution indeed gave me a result even though I had used the function before with my data being  in the form of pandas.Series. Furthermore, the breaks that are given as a result are not ordered from lower to higher as they are supposed to be and had been in the past. Do you have any idea what might be wrong ?

**Comment by frankg77** [comment]
> `jenkspy.jenks_breaks` does not natively support `pandas.Series`. You should transform your values into a numpy array first, using the `to_numpy` method (with something like `buurten_perfomance['A_obstacle'].to_numpy()`).
> 
> Hope this helps. Don't hesitate to tell me if you still have a problem.

This helped me automate a very annoying report at work, so thank you very much for this.
