### ISSUE TITLE
conda-forge wincertstore==0.2=py37_1002 error

### ISSUE THREAD

**Issue by DanGolding** [mthh/jenkspy#2]
Getting the following error when trying to install from conda-forge:

```
conda install -c conda-forge jenkspy
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-forge/win-64::wincertstore==0.2=py37_1002
  - jenkspy
Use "conda info <package>" to see the dependencies for each package.
```

Apparently it has to do with the conda-forge migration: https://stackoverflow.com/questions/52973918/unsatisfiableerror-conda-forge-3-7

**Comment by mthh** [comment]
Thanks for reporting this and for the StackOverflow link.
If I understand correctly there is not much I can do for now? Otherwise do not hesitate to make me a suggestion!

**Comment by DanGolding** [comment]
I'm not sure - based on the comment on the SO question it sounds like there is some action required by sklearn for this migration so there might be for jenkspy as well. But I honestly don't know anything about it.

**Comment by mthh** [comment]
I guess this now fixed.
