### ISSUE TITLE
Generating more than 1 date in the same break

### ISSUE THREAD

**Issue by jorgelpbarretob** [mthh/jenkspy#21]
>>breaks_jkp = []
>> for v in breaks:
 >>>>   idx = ts.index[ts == v]
 >>>>  breaks_jkp.append(idx)
>> breaks_jkp

[DatetimeIndex(['2021-04-18'], dtype='datetime64[ns]', name='date', freq=None),
 DatetimeIndex([_**'2021-05-14', '2021-06-11', '2021-09-27'**_], dtype='datetime64[ns]', name='date', freq=None),
 DatetimeIndex(['2021-07-13'], dtype='datetime64[ns]', name='date', freq=None),
 DatetimeIndex(['2021-07-04'], dtype='datetime64[ns]', name='date', freq=None),
 DatetimeIndex(['2021-09-03'], dtype='datetime64[ns]', name='date', freq=None)]

![Issue](https://user-images.githubusercontent.com/94770814/142780745-5c489a48-0c31-46af-ac08-165a98aca210.jpeg)

**Comment by mthh** [comment]
Sorry for the late answer.
Can you show an extract of your data (notably in `y` and `ts` variables) so that I can help you debug your code ?

**Comment by mthh** [comment]
I'm closing this issue but don't hesistate to open a new one if you have any problem.
