### ISSUE TITLE
How to get gvf using jenks object?

### ISSUE THREAD

**Issue by SSMK-wq** [mthh/jenkspy#24]
I am trying to get the `goodness of variance fit` using jenks example given in github readme.

I tried the below

      print(jnb.nb_class)
      print(jnb.group)
      print(jnb.goodness_of_variance_fit)

but this doesn't work.

How can I know what is the best number of groups that is chosen by `jnb` and what is the gvf for that split when compared to other splits?

**Comment by mthh** [comment]
The attribute `goodness_of_variance_fit` of the `JenksNaturalBreaks` classe is a method.  
It expects a list or a 1D numpy array as argument, and will use this list / array to compute the goodness of variance fit against the breaks that where computed when calling the `fit`method.

You can also use it to compute to goodness of variance fit on the list / array you used to compute the breaks :

```
my_array = [1, 2, 3, 2, 4, 12, 4, 6, 7, 8, 9, 1, 2, 10, 11, 4]

jnb = JenksNaturalBreaks(6)
jnb.fit(my_array)
jnb.goodness_of_variance_fit(my_array)
# Returns 0.9830674846625768

jnb = JenksNaturalBreaks(2)
jnb.fit(my_array)
jnb.goodness_of_variance_fit(my_array)
# Returns 0.8025903203817314
```

**Comment by mthh** [comment]
I added missing doctrings on `JenksNaturalBreaks` (it is in 0.2.3 release) and slightly improved the example in the README. I hope it helps.
Don't hesitate to reopen an issue if you need help using `jenkspy`
