### ISSUE TITLE
JenksNaturalBreaks(1) fails

### ISSUE THREAD

**Issue by pulquero** [mthh/jenkspy#28]
group() doesn't handle the edge case of n_classes=1 as inner_breaks_ is empty:
groups_ = [arr[arr <= self.inner_breaks_[0]]]

**Comment by mthh** [comment]
Thanks for reporting it.
I will fix it soon (probably tomorrow, but don't hesitate if you prefer to submit a pull request yourself in the meantime).

**Comment by mthh** [comment]
This has been fixed in 85c80e3.
