### ISSUE TITLE
Add Support python version 3.12

### ISSUE THREAD

**Issue by ni-todo-spot** [mthh/jenkspy#29]
Hello!
Would be sweet if support for py3.12 could be added..
Thanks in Advance!

**Comment by mthh** [comment]
I released 0.4.0 on PyPI, alongside with wheels for Python 3.12.

**Comment by ni-todo-spot** [comment]
> I released 0.4.0 on PyPI, alongside with wheels for Python 3.12.

YOU ROCK!
