### ISSUE TITLE
Segfault for `nan` and `inf` values

### ISSUE THREAD

**Issue by bnaul** [mthh/jenkspy#4]
But only sometimes. This is on MacoS:
```
[ins] In [1]: import jenkspy, numpy as np

[ins] In [2]: jenkspy.__version__
Out[2]: '0.1.4'

[ins] In [7]: jenkspy.jenks_breaks([0, 1, np.nan], 2)
Out[7]: [0.0, 0.0, nan]

[ins] In [9]: jenkspy.jenks_breaks([0, 1, 2, 3, 4, np.nan], 4)
[1]    60639 segmentation fault  ipython
```

**Comment by mthh** [comment]
Thanks for reporting this !
Indeed I can confirm the same behaviour on my GNU/Linux system (which is not surprising since nothing is done to handle this case for now)

Would you prefer to see an error to be raised ? Or only a warning + ignoring these `nan` / `inf` value ?

**Comment by mthh** [comment]
Yeah sure, the point is to avoid this segfault!
My last commit should fix it. I will publish a new release on PyPi tomorrow.

**Comment by mthh** [comment]
This is fixed by ignoring NaN/Inf values (and warning the user about that).
Version 0.1.5 containing this fix has been released on PyPi.
Thx again!
