### ISSUE TITLE
Are breaks inclusive or exclusive?

### ISSUE THREAD

**Issue by paulvezzetti** [mthh/jenkspy#6]
In your example:

>>> jenks_breaks(
            [1.3, 7.1, 7.3, 2.3, 3.9, 4.1, 7.8, 1.2, 4.3, 7.3, 5.0, 4.3],
            nb_class = 3)  # Should output (1.2, 2.3, 5.0, 7.8)

Are the classes/groups:
[1.2, 1.3] [2.3, 4.1, 4.3, 4.3] [5.0, 7.1, 7.3, 7.3, 7.8]
or?
[1.2, 1.3, 2.3] [4.1, 4.3, 4.3, 5.0] [7.1, 7.3, 7.3, 7.8]

My interpretation is that it is the first. However, the second seems like a better grouping.

**Comment by mthh** [comment]
The returned breaks [1.2, 2.3, 5.0, 7.8] for your example should be read like this :

|  Interval  |  Count |
|-------------|-------|
| [1.20, 2.30] |     3 |
| (2.30, 5.00] |     5 |
| (5.00, 7.80] |     4 |

or [1.2, 1.3, 2.3]  [3.9, 4.1, 4.3, 4.3, 5.0] [7.1, 7.3, 7.3, 7.8] (your second proposal, which is, indeed, a better grouping !)

**Comment by paulvezzetti** [comment]
Awesome! Thanks for the quick reply.
