### ISSUE TITLE
breaks including min and max

### ISSUE THREAD

**Issue by rue-a** [mthh/jenkspy#8]
Hi found the behavior to include the min and max values into the breaks very unintuitive. I had to go into your code, because I thought there is something faulty. Right there I found your comment, which made everything clear. 

So I think you should either communicate this behavior in the README or remove it. Apart from that, nice tool!

**Comment by mthh** [comment]
Thanks for your comment !

I changed a bit the README file, do you think it's better ?
(otherwise, don't hesitate to make a PR !)
