### ISSUE TITLE
Jenkspy 64-bit version?

### ISSUE THREAD

**Issue by LayneSeely** [mthh/jenkspy#9]
I am very thankful that I have found JenksPy - it has helped me greatly and likely will in the future as well.  My only concern \ question is will there be a 64-bit version available?
Layne

**Comment by mthh** [comment]
Thanks for your comment !

What do you mean specifically by "a 64-bit version" ?
Currently there is wheels on PyPi for windows (Python 2.7 and Python 3.4 to 3.7) for both 32-bit and 64-bit systems.

I made some changes and I will release a new version. Wheels will be provided (on PyPi) for Python 3.4 to 3.8 (for both 32 and 64-bits systems).
Does that meet your need?

**Comment by LayneSeely** [comment]
Hey Matthieu:

Thank you very much for replying to me.  I was able to get your script running with the 64-bit version of Python after I fixed some pathing errors on my end.

Layne
